steps:
  - name: "gcr.io/cloud-builders/docker"
    id: build
    entrypoint: "bash"
    args:
      - -c
      - |
        docker build -t gcr.io/$PROJECT_ID/quiz-me:latest --build-arg PUBLIC_URL=$$PUBLIC_URL --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY --build-arg CLERK_SECRET_KEY=$$CLERK_SECRET_KEY --build-arg DATABASE_URL=$$DATABASE_URL --build-arg UPLOADTHING_SECRET=$$UPLOADTHING_SECRET --build-arg UPLOADTHING_APP_ID=$$UPLOADTHING_APP_ID --build-arg OPENAI_API_KEY=$$OPENAI_API_KEY --build-arg STRIPE_API_KEY=$$STRIPE_API_KEY --build-arg STRIPE_WEBHOOK_SECRET=$$STRIPE_WEBHOOK_SECRET --build-arg STRIPE_PRICE_ID=$$STRIPE_PRICE_ID --build-arg DEEPGRAM_API_KEY=$$DEEPGRAM_API_KEY .
    secretEnv:
      [
        "PUBLIC_URL",
        "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY",
        "DATABASE_URL",
        "CLERK_SECRET_KEY",
        "UPLOADTHING_APP_ID",
        "UPLOADTHING_SECRET",
        "OPENAI_API_KEY",
        "DEEPGRAM_API_KEY",
        "STRIPE_API_KEY",
        "STRIPE_WEBHOOK_SECRET",
        "STRIPE_PRICE_ID",
      ]
  - name: "gcr.io/cloud-builders/docker"
    id: push
    entrypoint: "bash"
    args:
      - -c
      - |
        docker push gcr.io/$PROJECT_ID/quiz-me:latest
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    id: deploy
    entrypoint: "bash"
    args:
      - -c
      - |
        gcloud run services update quiz-me --platform=managed --image=gcr.io/$PROJECT_ID/quiz-me:latest --region=asia-southeast1 --quiet

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/PUBLIC_URL/versions/latest
      env: "PUBLIC_URL"
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY/versions/latest
      env: "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
    - versionName: projects/$PROJECT_ID/secrets/CLERK_SECRET_KEY/versions/latest
      env: "CLERK_SECRET_KEY"
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: "DATABASE_URL"
    - versionName: projects/$PROJECT_ID/secrets/UPLOADTHING_SECRET/versions/latest
      env: "UPLOADTHING_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/UPLOADTHING_APP_ID/versions/latest
      env: "UPLOADTHING_APP_ID"
    - versionName: projects/$PROJECT_ID/secrets/OPENAI_API_KEY/versions/latest
      env: "OPENAI_API_KEY"
    - versionName: projects/$PROJECT_ID/secrets/STRIPE_API_KEY/versions/latest
      env: "STRIPE_API_KEY"
    - versionName: projects/$PROJECT_ID/secrets/STRIPE_WEBHOOK_SECRET/versions/latest
      env: "STRIPE_WEBHOOK_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/STRIPE_PRICE_ID/versions/latest
      env: "STRIPE_PRICE_ID"
    - versionName: projects/$PROJECT_ID/secrets/DEEPGRAM_API_KEY/versions/latest
      env: "DEEPGRAM_API_KEY"
